### PR TITLE
Add count method to complement the search method

### LINKED ISSUE #5: Feature Request: addition of searchCount method (or count)
`Obuchmann\OdooJsonRpc\Odoo` seems to be missing a way to get the count of a search result.

While `Odoo->search` uses `Odoo\Endpoint->search`,
there's currently no alternative to reach `Odoo\Endpoint->count` from the `Odoo` provider.

### PR DESCRIPTION
**Pull request by xewl**
closes #5

### CODE REVIEW

**Comment by obuchmann** [comment]
Thank you for your PR. Could you please add a test in the OdooTest class.

**Comment by xewl** [comment]
Things I notice:

Odoo `Request` classes like `Search`, `SearchRead` expect a `Domain` even though the wrapper methods for them.

Seems like there's more tests to add, outside of this one, even though `Count` can perfectly be done with the `Search` Request class on its own, as long as a default/empty `Domain` is provided instead of `null`.

By this logic, I also adjusted the `ObjectEndpoint` class, so the following methods also null coalesce a default empty `Domain` object, like the model method does, and their Request classes and the Odoo API respectively expect:
- count
- search
- searchRead

I renamed 2 tests that are actually testing the Model way, to include "Model"
- testCount -> testModelCount
- testCountWhere -> testModelCountWhere
- testSearchRead -> testModelSearchRead
- testSearchReadFields -> testModelSearchReadFields

and added:
- testDirectCount
- testDirectCountWhere
- testDirectSearchRead
- testDirectSearchReadFields

These however may need to be split to separate files, as the layer of their use is different (Direct calls vs Eloquent-like).

**Comment by obuchmann** [comment]
Hi @xewl,
i'm sorry, i have been very busy and had no time to review.

Your PR looks very good! 
Good point with splitting the tests, we should consider this in a new PR.

Thank you for your contribution!

**Comment by xewl** [comment]
Happy NY @obuchmann 
No worries, glad you found the time eventually :D 
Thanks for the merge & version bump!

**Pull request merged**
